apiVersion: v1
kind: ConfigMap
metadata:
  name: ged-admin
data:
  APP_DEBUG: "false"
  APP_ENV: production
  APP_NAME: "ADM Panel"

  DB_CONNECTION: pgsql
  DB_WRITER_HOST: postgres-writer
  DB_WRITER_PORT: "5432"
  DB_READER_HOST: postgres-reader
  DB_READER_PORT: "5432"
  DB_DATABASE: db_admin

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  LOG_CHANNEL: stdout
  LOG_LEVEL: info

  BROADCAST_DRIVER: log

  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  SESSION_LIFETIME: "120"
  QUEUE_CONNECTION: redis

  FILESYSTEM_DISK: local
  
  AWS_REGION: sa-east-1
  AWS_DEFAULT_REGION: sa-east-1
  AWS_BUCKET: ged-image-store

  DOMAIN_NAME: optimus.dev.br

  CLIENT_PVC_IMAGES: images-pvc
  CLIENT_CONTAINER: ged-client-nginx

  NODE_PORTS: "30000-32767"
